# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$task = "11"
$vm1 = "cent-1"
$box1 = "chef/centos-6.5"
$vm2 = "cent-2"
$box2 = "chef/centos-6.5"
$vm3 = "cent-3"
$box3 = "chef/centos-6.5"
#$box3 = "ubuntu/trusty64"
$vm4 = "puppet"
$box4 = "chef/centos-6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.

  config.vm.define "#{$vm1}" do |vm1|
    vm1.vm.box = "#{$box1}"
    vm1.vm.hostname = "#{$vm1}"
    vm1.vm.network "private_network", ip: "192.168.100.10"
    vm1.vm.provision :shell, inline: "sudo rpm -ivhf http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
    vm1.vm.provision :shell, inline: "sudo yum install -y puppet"
      config.vm.provider "virtualbox" do |v|
        v.name = "#{$task}-#{$vm1}"
        v.memory = 2048
      end
  end

  config.vm.define "#{$vm2}" do |vm2|
    vm2.vm.box= "#{$box2}"
    vm2.vm.hostname = "#{$vm2}"
    vm2.vm.network "private_network", ip: "192.168.100.20"
    vm2.vm.provision :shell, inline: "sudo rpm -ivhf http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
    vm2.vm.provision :shell, inline: "sudo yum install -y puppet"
      config.vm.provider "virtualbox" do |v|
        v.name = "#{$task}-#{$vm2}"
        v.memory = 2048
      end
  end
  
  config.vm.define "#{$vm3}" do |vm3|
    vm3.vm.box = "#{$box3}"
    vm3.vm.hostname = "#{$vm3}"
    vm3.vm.network "private_network", ip: "192.168.100.30"
    vm3.vm.provision :shell, inline: "sudo rpm -ivhf http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
    vm3.vm.provision :shell, inline: "sudo yum install -y puppet"
      config.vm.provider "virtualbox" do |v|
        v.name = "#{$task}-#{$vm3}"
        v.memory = 2048
      end
  end

  config.vm.define "#{$vm4}" do |vm4|
    vm4.vm.box = "#{$box4}"
    vm4.vm.hostname = "#{$vm4}"
    vm4.vm.network "private_network", ip: "192.168.100.40"
    vm4.vm.provision :shell, inline: "sudo rpm -ivhf http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm"
    vm4.vm.provision :shell, inline: "sudo yum install -y puppet-server"
      config.vm.provider "virtualbox" do |v|
        v.name = "#{$task}-#{$vm4}"
        v.memory = 2048
      end
    vm4.vm.synced_folder "puppet-lab", "/etc/puppet", owner: "root", group: "root"
  end

$chef_solo = <<SCRIPT
curl -L https://www.opscode.com/chef/install.sh | sudo bash
sudo git clone https://github.com/1n/chef-jboss.git -b task7 /root/chef-jboss/
sudo chef-solo -c /root/.chef/solo.rb -L /vagrant/chef-jboss/cookbooks/jboss/chef.run.log
SCRIPT

$chef_server = <<SCRIPT
wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.4-1_amd64.deb
sudo dpkg -i chef-server_11.1.4-1_amd64.deb 
sudo chef-server-ctl reconfigure
SCRIPT

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with CFEngine. CFEngine Community packages are
  # automatically installed. For example, configure the host as a
  # policy server and optionally a policy file to run:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.am_policy_hub = true
  #   # cf.run_file = "motd.cf"
  # end
  #
  # You can also configure and bootstrap a client to an existing
  # policy server:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.policy_server_address = "10.0.2.15"
  # end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  # config.vm.provision "puppet" do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "site.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { mysql_password: "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
